/**
 * SERVICE × COUNTY landing pages — /locations/[county]/[service]/
 *
 * These are deliberately NOT templated. The 26 county pages share one layout
 * and roughly 120 unique words each, which is the doorway-page pattern Google
 * suppresses; that is why /locations/limerick/ is indexed but nowhere on page
 * one. Every page in this file is written from scratch for one service in one
 * county, and none of it is generated by string interpolation.
 *
 * Add a county only when there is genuinely something specific to say about
 * it. Three real pages beat thirty spun ones.
 */

export interface ServicePage {
  county: string;
  countySlug: string;
  service: string;
  serviceSlug: string;
  title: string;
  description: string;
  h1: string;
  /** Opening — establishes local knowledge before it sells anything. */
  intro: string[];
  sections: {
    heading: string;
    body: string[];
    /** Optional bulleted detail under the prose. */
    list?: { title: string; body: string }[];
  }[];
  areas: { heading: string; body: string; towns: string[] };
  pricing: { heading: string; body: string[] };
  faqs: { q: string; a: string }[];
  related: { label: string; href: string }[];
}

/* ────────────────────────────────────────────────────────────────
   LIMERICK
   ──────────────────────────────────────────────────────────────── */

const limerickDigitalMarketing: ServicePage = {
  county: "Limerick",
  countySlug: "limerick",
  service: "Digital marketing",
  serviceSlug: "digital-marketing",
  title: "Digital Marketing Limerick | Agency for Limerick Businesses",
  description:
    "A digital marketing agency working with Limerick businesses: Google Ads, Meta ads, SEO, web design and social, from Limerick city and Castletroy to Newcastle West and Adare. Reported in enquiries, not impressions.",
  h1: "Digital marketing in Limerick, measured in enquiries.",
  intro: [
    "Limerick is not one market, and campaigns that treat it as one waste most of their budget. The city and its suburbs — Castletroy, Dooradoyle, Raheen, Corbally, Annacotty — behave like a mid-sized urban catchment with a young population, two large third-level campuses and a steady flow of people moving in for work. West Limerick, out through Newcastle West, Abbeyfeale and Rathkeale, is a different economy entirely: smaller towns, longer travel distances, and businesses whose customers come from three or four parishes rather than three or four postcodes.",
    "That split matters more than any tactic. A radius around Limerick city centre picks up students who will never buy from you. A county-wide campaign spends half its budget in places you would not drive to. We build Limerick campaigns around the areas a business will actually travel to and the customers it can actually serve, and we report the number that matters: how many people got in touch.",
  ],
  sections: [
    {
      heading: "What we actually run for Limerick businesses",
      body: [
        "Five services, and most Limerick clients need two of them rather than all five. We would rather run one channel properly than spread a small budget across everything and have nothing work.",
      ],
      list: [
        {
          title: "Google Ads",
          body: "The fastest route to the phone ringing, because you are reaching people at the moment they search. For a Limerick trade or professional service this usually means a tight geographic radius, negative keywords that strip out the university and course-related searches Limerick generates in volume, and call tracking so you can hear what a lead is actually worth.",
        },
        {
          title: "Meta ads",
          body: "Facebook and Instagram still carry an unusual amount of weight in Limerick and the surrounding counties, particularly for home improvement, hospitality and anything with a strong visual before-and-after. Local community pages are widely followed and word travels. We use lead forms and click-to-message rather than sending cold traffic to a website that was not built to convert it.",
        },
        {
          title: "SEO",
          body: "The long game, and the one that compounds. For Limerick this means the service-plus-place searches people actually type, the on-page foundations most local sites never had, and a Google Business Profile that is filled in properly rather than left at the defaults.",
        },
        {
          title: "Web design",
          body: "Most Limerick businesses we speak to do not have a traffic problem so much as a conversion problem: people are already finding them and leaving. A site that loads fast, works on a phone and asks for the enquiry usually lifts results more than any increase in ad spend.",
        },
        {
          title: "Social media management",
          body: "Run for you, in the voice of the business you actually are. Useful when your customers check whether you are still trading before they call — which, in a market this size, they do.",
        },
      ],
    },
    {
      heading: "Why most Limerick campaigns underperform",
      body: [
        "We have looked at enough Limerick accounts to see the same four problems again and again, and none of them are exotic.",
      ],
      list: [
        {
          title: "The radius is wrong",
          body: "A 25km circle drawn on Limerick city reaches into Clare and Tipperary and picks up a great deal of traffic from people who will never travel to you. It also swallows the university catchment, which generates enormous search volume with no commercial intent for most businesses.",
        },
        {
          title: "Course searches are not filtered out",
          body: "Limerick has two large institutions teaching marketing, business and technology. Searches like 'digital marketing Limerick' return degree courses alongside agencies for exactly that reason. If you advertise in this county without negative keywords for courses, jobs, and salaries, you will pay for clicks from students.",
        },
        {
          title: "Nobody is tracking calls",
          body: "In a market where most enquiries arrive by phone rather than by form, an account with no call tracking is being optimised blind. Half the results are invisible, so the wrong campaigns get cut.",
        },
        {
          title: "The website was never the point",
          body: "Ads get judged on cost per click when the actual problem is that the landing page loads in six seconds, buries the phone number, and was last updated in 2019.",
        },
      ],
    },
    {
      heading: "How we work",
      body: [
        "There is no office visit, no retainer dressed up as a partnership and no quarterly strategy deck. You deal directly with the person running your account.",
        "Week one we get access, fix what is obviously broken and set up tracking so that the numbers from week two onwards are real. From there you get one short report a week — enquiries, cost per enquiry, and what we changed — in plain English. If something is not working you will hear it from us before you notice it yourself.",
      ],
    },
  ],
  areas: {
    heading: "Where in Limerick we work",
    body: "Campaigns are built around the areas you actually serve rather than the county as a whole, so the budget goes on people who can realistically become customers. These are the areas that come up most often for Limerick clients.",
    towns: [
      "Limerick city centre",
      "Castletroy",
      "Dooradoyle",
      "Raheen",
      "Corbally",
      "Annacotty",
      "Castleconnell",
      "Adare",
      "Newcastle West",
      "Abbeyfeale",
      "Kilmallock",
      "Rathkeale",
      "Croom",
      "Patrickswell",
      "Caherdavin",
      "Mungret",
    ],
  },
  pricing: {
    heading: "What it costs",
    body: [
      "€1,500 a month covers one advertising channel — Meta or Google — managed properly, all of your social media run, and every lead followed up. €2,500 a month covers both channels, a new website, and everything in the first package.",
      "Month to month, cancel any time, no setup fee. Advertising spend is separate and is paid by you directly to Google or Meta from your own account, so you keep control of the budget and you own the ad account when you leave.",
      "If a website is the only thing you need, that is a one-off €1,500 with no monthly fee at all.",
    ],
  },
  faqs: [
    {
      q: "Are you based in Limerick?",
      a: "No, and we will not pretend otherwise. Dublin Growth Digital is based in Dublin and works with businesses in every county in Ireland, Limerick included. Everything — campaign setup, reporting, calls and the free audit — is done remotely and by phone. If having someone who can call to your unit in person matters to you, hire a Limerick agency; that is a legitimate reason to choose one and we would rather say so than waste your time.",
    },
    {
      q: "Will I show up in the Google map results for Limerick?",
      a: "Only if you have a real address in Limerick. Google's map results are driven by verified physical location and proximity to the person searching, which is why every business in the Limerick map pack has a street address in the city or county. If you have a Limerick premises we will get your Google Business Profile into proper shape to compete there. If you do not, we focus on the ordinary search results and on paid, where location is not a barrier.",
    },
    {
      q: "How quickly will I see something?",
      a: "Paid channels produce enquiries in days — Google Ads usually inside a week of going live. SEO is measured in months, not weeks, and anyone promising otherwise is selling you something. We are explicit about which of the two you are buying before you commit.",
    },
    {
      q: "Do you work with businesses outside Limerick city?",
      a: "Yes, and west Limerick is a genuinely different job. Newcastle West, Abbeyfeale and Rathkeale draw from a wide rural catchment with less competition and cheaper clicks, but you need the geography and the messaging to match how far people will realistically travel.",
    },
    {
      q: "What size of business do you work with?",
      a: "Owner-run businesses that answer their own phone, typically between two and twenty people. We are not the right fit for a business that needs a large in-house team coordinated, and we are not cheap enough to make sense for someone testing marketing for the first time with a €200 budget.",
    },
    {
      q: "Can I see what you would do before paying anything?",
      a: "Yes. Ask for the free growth audit and we will check where you appear in Limerick search results, who is outranking you, what your competitors are advertising, and what your website is doing to visitors when they land. It comes back as a PDF within 24 hours and there is no call attached to it.",
    },
  ],
  related: [
    { label: "Social media marketing in Limerick", href: "/locations/limerick/social-media-marketing/" },
    { label: "Web design in Limerick", href: "/locations/limerick/web-design/" },
    { label: "All Limerick services", href: "/locations/limerick/" },
  ],
};

const limerickSocial: ServicePage = {
  county: "Limerick",
  countySlug: "limerick",
  service: "Social media marketing",
  serviceSlug: "social-media-marketing",
  title: "Social Media Marketing Limerick | Managed Social & Paid Ads",
  description:
    "Social media marketing for Limerick businesses: Facebook and Instagram content and paid campaigns, managed end to end. From Limerick city and Castletroy to Newcastle West and Adare.",
  h1: "Social media marketing in Limerick that produces customers, not followers.",
  intro: [
    "Social media works unusually well in Limerick, and the reason is size. It is a county where a good recommendation still travels through community pages, parish groups and local buy-and-sell forums faster than through any advertising platform. A single well-received post about a job done well in Castletroy or Newcastle West reaches people no targeting setting can buy.",
    "That is also the trap. Reach in a market this size is easy and almost meaningless on its own. Plenty of Limerick businesses have four thousand followers and no idea whether a single customer ever came from them. What we run is built the other way around: the content exists to produce enquiries, and we report on the enquiries.",
  ],
  sections: [
    {
      heading: "What managing your social actually involves",
      body: [
        "Two halves, and both are needed. Content on its own builds an audience slowly and unpredictably. Paid on its own reaches people who look you up, find a page last posted to in 2023, and quietly decide against you.",
      ],
      list: [
        {
          title: "The content, written and posted for you",
          body: "A steady schedule across Facebook and Instagram in the voice of the business you actually run. Work you have completed, the people who did it, questions customers keep asking, prices and availability when it helps. You send photos from the van or the shop floor; we do the rest.",
        },
        {
          title: "Paid campaigns behind the content",
          body: "The posts that earn a genuine response get money behind them and go out to a targeted Limerick audience. This is the part that turns a page into a channel, and it is where most self-managed social stops.",
        },
        {
          title: "Lead forms and click-to-message",
          body: "Enquiries captured inside Facebook and Instagram rather than sent to a website to get lost. In practice this roughly doubles the number of people who complete an enquiry on a phone.",
        },
        {
          title: "Replies handled",
          body: "Comments and messages answered within the working day. A large share of social enquiries in a local market arrive as a message rather than a form, and unanswered messages are lost customers.",
        },
        {
          title: "One report a week",
          body: "Enquiries, cost per enquiry, and what we changed. Not reach, not impressions, not engagement rate.",
        },
      ],
    },
    {
      heading: "Which Limerick businesses this suits",
      body: [
        "Social is not the right first channel for everyone, and we will say so if it is not. It works hardest when the work is visual, the decision is emotional or discretionary, and the customer is local.",
        "That means home improvement and trades where before-and-after photographs do the selling. Salons, barbers, clinics, gyms and studios where people want to see the room and the staff before they book. Restaurants, cafés and anywhere in the Limerick hospitality trade where a Friday post fills a Saturday. Retailers who need people to know they are still there and what has just come in.",
        "It works far less well for emergency services and for anything bought at the exact moment of need. If somebody's boiler has failed they are searching Google, not scrolling Instagram — and for those businesses we would put you on search first and social second.",
      ],
    },
    {
      heading: "What you have to do",
      body: [
        "Send us photographs. That is genuinely the whole of it.",
        "The single reason managed social fails is that the agency runs out of real material and starts posting stock images and motivational quotes, which any customer can spot instantly. A few phone photos a week of actual work, actual staff and actual premises will outperform anything we could buy. We handle the writing, the scheduling, the design, the ad spend and the replies.",
      ],
    },
  ],
  areas: {
    heading: "Limerick areas we target",
    body: "Paid social lets us draw the audience tightly around where your customers actually are, which in a county shaped like this one matters a great deal. City-based businesses and west Limerick businesses get different targeting entirely.",
    towns: [
      "Limerick city centre",
      "Castletroy",
      "Dooradoyle",
      "Raheen",
      "Corbally",
      "Caherdavin",
      "Annacotty",
      "Castleconnell",
      "Adare",
      "Patrickswell",
      "Newcastle West",
      "Abbeyfeale",
      "Rathkeale",
      "Kilmallock",
      "Croom",
      "Mungret",
    ],
  },
  pricing: {
    heading: "What it costs",
    body: [
      "Social media management is included in the €1,500 a month package alongside one advertising channel and full lead follow-up. It is not sold as a separate line item, because a page being posted to without any budget behind it rarely earns its keep.",
      "€2,500 a month adds the second advertising channel and a new website.",
      "Month to month, cancel any time. Ad spend is paid by you directly to Meta from your own account, and the account stays yours.",
    ],
  },
  faqs: [
    {
      q: "Do I need to be on TikTok?",
      a: "Probably not. For most Limerick businesses Facebook is still where the buying audience is, with Instagram second, and doing those two properly beats spreading thin across four platforms. If your customers are genuinely under thirty we will tell you and we will plan for it, but we are not going to sell you a TikTok strategy to look modern.",
    },
    {
      q: "How many posts a week?",
      a: "Three to five, which is enough to stay visible without becoming noise. Frequency is far less important than whether the posts are real. One genuine photograph of a finished job in Raheen will do more than seven designed graphics.",
    },
    {
      q: "Can you use my existing Facebook page?",
      a: "Yes, and we usually should. An existing page carries followers, reviews and history that a new one throws away. We would want editor access rather than ownership — the page stays yours throughout and you can remove our access the day you decide to stop.",
    },
    {
      q: "What if I do not have any photos?",
      a: "Then we start by fixing that, because it is the constraint on everything else. In practice it means five minutes on a job or in the premises with a phone camera and a short list from us of what to capture. It is not a reason not to start, but it is the one part nobody can do for you.",
    },
    {
      q: "Do you guarantee a number of followers?",
      a: "No. Follower counts can be bought and are worth nothing; we have no interest in selling you a number that does not turn into work. What we report is how many people enquired and what each enquiry cost.",
    },
    {
      q: "Who replies to comments and messages?",
      a: "We do, within the working day, for anything general — prices, availability, opening hours, whether you cover a particular area. Anything that needs your judgement gets passed straight to you rather than guessed at.",
    },
  ],
  related: [
    { label: "Digital marketing in Limerick", href: "/locations/limerick/digital-marketing/" },
    { label: "Web design in Limerick", href: "/locations/limerick/web-design/" },
    { label: "All Limerick services", href: "/locations/limerick/" },
  ],
};

const limerickWeb: ServicePage = {
  county: "Limerick",
  countySlug: "limerick",
  service: "Web design",
  serviceSlug: "web-design",
  title: "Web Design Limerick | Website Design & Development, €1,500",
  description:
    "Web design and development for Limerick businesses. A custom site, written and built for you, live in ten working days for a one-off €1,500. No monthly fee and you own every file.",
  h1: "Web design and development for Limerick businesses.",
  intro: [
    "Most Limerick businesses that come to us do not have a traffic problem. People are already finding them — through search, through a recommendation, through a Facebook page — and then leaving without getting in touch. The site loads slowly, it is awkward on a phone, the phone number is three taps away, and it says what the business does without ever asking anybody to do anything.",
    "That is a conversion problem, and it is much cheaper to fix than a traffic problem. Doubling the share of visitors who make contact costs a fraction of doubling the number of visitors, and it makes every other channel you run worth more at the same time.",
  ],
  sections: [
    {
      heading: "What you get",
      body: [
        "One fixed price of €1,500, paid once, for a site designed and written from scratch for your business. No monthly fee, no contract, and no retainer at the end of it.",
      ],
      list: [
        {
          title: "Designed for you, not assembled from a template",
          body: "Up to seven pages, laid out around what your customers need to see before they pick up the phone — not a stock theme with your logo dropped into the corner.",
        },
        {
          title: "Every word written for you",
          body: "Headlines, service pages, the about page, calls to action. You do not write a sentence. We read your reviews, your competitors and your existing site first.",
        },
        {
          title: "Built for the phone",
          body: "Designed on mobile and scaled up. Most of the people who find a Limerick business are on a phone, often standing somewhere, often in a hurry.",
        },
        {
          title: "Technical SEO from day one",
          body: "Page titles, meta descriptions, heading structure, schema markup, sitemap and robots.txt, plus Google Search Console and Analytics set up in your name. The foundations that decide whether the site can rank at all.",
        },
        {
          title: "Your Google Business Profile rebuilt",
          body: "Categories, services and description rewritten around the searches you want to win in Limerick. For a local business this is often the fastest single improvement available.",
        },
        {
          title: "Hosting, SSL and your domain connected",
          body: "The first twelve months included. We connect the domain you already own or register a new one for you.",
        },
      ],
    },
    {
      heading: "Ten working days, and about forty minutes of your time",
      body: [
        "The reason website projects normally drag on for months is that they are run as a conversation. This one is run as a build with a finish date.",
        "You answer six short questions and send your logo. We research and write, then design and build, and you get a preview link halfway through so nothing is a surprise. On day eight you send one list of everything you want changed, however long that list is. We make the changes, connect the domain and launch. Then you get thirty days of unlimited further changes at no charge.",
        "Your site does not go live until you have looked at it and said it is right. Unlimited revision rounds, no cut-off date.",
      ],
    },
    {
      heading: "Web development, and where the line is",
      body: [
        "This covers business websites: service pages, galleries, contact and quote forms, click-to-call, maps, and connections to booking or payment tools you already use such as Stripe, Calendly, Square or Fresha.",
        "It does not cover custom software. A large e-commerce store with live stock control, a client portal, a booking engine built from scratch or a mobile app are all different jobs with different prices. Tell us before you pay and we will either quote it properly or tell you we are not the right people for it.",
      ],
    },
  ],
  areas: {
    heading: "Working with Limerick businesses",
    body: "The whole process runs by email, WhatsApp and one optional twenty-minute call, so it makes no difference to the price or the timeline where in the county you are. We build for businesses across Limerick city and the county.",
    towns: [
      "Limerick city centre",
      "Castletroy",
      "Dooradoyle",
      "Raheen",
      "Corbally",
      "Caherdavin",
      "Annacotty",
      "Mungret",
      "Castleconnell",
      "Adare",
      "Patrickswell",
      "Newcastle West",
      "Abbeyfeale",
      "Rathkeale",
      "Kilmallock",
      "Croom",
    ],
  },
  pricing: {
    heading: "What it costs",
    body: [
      "€1,500, paid once. That covers the design, the writing, the build, the launch, the SEO foundations, the analytics setup, the Google Business Profile work, the first twelve months of hosting and thirty days of unlimited changes after launch.",
      "There is no monthly fee and no contract. Every file, login and account is created in your name from the start, so you can take the site elsewhere whenever you want.",
      "If you also want advertising run afterwards, that is a separate decision made after the site is live, and nobody has to buy it.",
    ],
  },
  faqs: [
    {
      q: "Is €1,500 really the whole price for a Limerick business?",
      a: "Yes — the price is the same wherever you are in Ireland. It covers everything listed above including the first twelve months of hosting and the thirty days of free changes after launch. There is no setup fee and no invoice at the end for work that turned out to be 'out of scope'.",
    },
    {
      q: "Who owns the website when it is finished?",
      a: "You do, entirely. The domain, the files, the hosting account, the analytics and the Search Console property are all in your name from the beginning. There is no situation where you have to ask our permission or buy your own site back, which is not true of every web designer.",
    },
    {
      q: "Will the new site actually rank in Limerick?",
      a: "The build gives it the foundations to rank — proper titles, structure, schema, speed, and a Google Business Profile in order — and for a business with little competition that is often enough on its own. For a competitive Limerick search like web design or digital marketing, a well-built site is necessary but not sufficient; ranking also needs time, reviews and other sites linking to you. We will tell you honestly which situation you are in.",
    },
    {
      q: "I already have a website. Is it worth replacing?",
      a: "If it brings you steady enquiries, keep it. If it is more than three or four years old, looks wrong on a phone, or you cannot remember the last enquiry that came through it, then it is quietly costing you more than €1,500 a year in work you never hear about.",
    },
    {
      q: "Do I need to come to a meeting?",
      a: "No. There is one optional twenty-minute call if you would rather talk than type; otherwise the whole thing runs on a six-question form, email and WhatsApp.",
    },
    {
      q: "What happens if I want changes in a year?",
      a: "Small things we do as a favour. Anything substantial is charged at a flat rate agreed in advance, always quoted before we start. You are never locked into a support plan to keep your own website working.",
    },
  ],
  related: [
    { label: "Digital marketing in Limerick", href: "/locations/limerick/digital-marketing/" },
    { label: "Social media marketing in Limerick", href: "/locations/limerick/social-media-marketing/" },
    { label: "The full €1,500 website offer", href: "/offer/" },
  ],
};

export const servicePages: ServicePage[] = [
  limerickDigitalMarketing,
  limerickSocial,
  limerickWeb,
];

export const servicePageBy = (countySlug: string, serviceSlug: string) =>
  servicePages.find(
    (p) => p.countySlug === countySlug && p.serviceSlug === serviceSlug,
  );

export const servicePagesForCounty = (countySlug: string) =>
  servicePages.filter((p) => p.countySlug === countySlug);
